//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/InputSystem/AddControllers.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @AddControllers : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @AddControllers()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""AddControllers"",
    ""maps"": [
        {
            ""name"": ""AddControllersMap"",
            ""id"": ""3c0e4f2f-7ba1-407d-ad07-ee900f9acfb6"",
            ""actions"": [
                {
                    ""name"": ""JoinPlayer"",
                    ""type"": ""Button"",
                    ""id"": ""ed4eedd1-cd8e-4dbd-bcff-00485a3cdd8c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ba648af7-4f21-45ce-b89c-c981f5134342"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JoinPlayer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4634e968-fd74-44a9-8de0-e7ac4ab63dfc"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JoinPlayer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // AddControllersMap
        m_AddControllersMap = asset.FindActionMap("AddControllersMap", throwIfNotFound: true);
        m_AddControllersMap_JoinPlayer = m_AddControllersMap.FindAction("JoinPlayer", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // AddControllersMap
    private readonly InputActionMap m_AddControllersMap;
    private IAddControllersMapActions m_AddControllersMapActionsCallbackInterface;
    private readonly InputAction m_AddControllersMap_JoinPlayer;
    public struct AddControllersMapActions
    {
        private @AddControllers m_Wrapper;
        public AddControllersMapActions(@AddControllers wrapper) { m_Wrapper = wrapper; }
        public InputAction @JoinPlayer => m_Wrapper.m_AddControllersMap_JoinPlayer;
        public InputActionMap Get() { return m_Wrapper.m_AddControllersMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(AddControllersMapActions set) { return set.Get(); }
        public void SetCallbacks(IAddControllersMapActions instance)
        {
            if (m_Wrapper.m_AddControllersMapActionsCallbackInterface != null)
            {
                @JoinPlayer.started -= m_Wrapper.m_AddControllersMapActionsCallbackInterface.OnJoinPlayer;
                @JoinPlayer.performed -= m_Wrapper.m_AddControllersMapActionsCallbackInterface.OnJoinPlayer;
                @JoinPlayer.canceled -= m_Wrapper.m_AddControllersMapActionsCallbackInterface.OnJoinPlayer;
            }
            m_Wrapper.m_AddControllersMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @JoinPlayer.started += instance.OnJoinPlayer;
                @JoinPlayer.performed += instance.OnJoinPlayer;
                @JoinPlayer.canceled += instance.OnJoinPlayer;
            }
        }
    }
    public AddControllersMapActions @AddControllersMap => new AddControllersMapActions(this);
    public interface IAddControllersMapActions
    {
        void OnJoinPlayer(InputAction.CallbackContext context);
    }
}
